import Reimbursement from "@/database/reimbursement-schema";
import { Types } from "mongoose";

export const data: Reimbursement[] = [
  {
    organization: new Types.ObjectId(1),
    reportName: "examplename",
    recipientName: "Billy Bob",
    recipientEmail: "billybob@gmail.com",
    transactionDate: new Date("2023-01-01"),
    amount: 500,
    paymentMethod: "Venmo",
    purpose: "Reimbursement for cultural booth event",
    receiptLink: "www.google.com",
    status: "Paid",
    comment: "",
  },
  {
    organization: new Types.ObjectId(2),
    reportName: "2exampname",
    recipientName: "Jill Andrews",
    recipientEmail: "jillandrews@gmail.com",
    transactionDate: new Date("2023-02-21"),
    amount: 1234.32,
    paymentMethod: "Paypal",
    purpose: "Reimbursement for lunch catering",
    receiptLink: "www.google.com",
    status: "On Hold",
    comment: "",
  },
  {
    organization: new Types.ObjectId(3),
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    comment: "",
  },
  {
    organization: new Types.ObjectId(4),
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    comment: "",
  },
  {
    organization: new Types.ObjectId(5),
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    comment: "",
  },
  {
    organization: new Types.ObjectId(6),
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    comment: "",
  },
  {
    organization: new Types.ObjectId(7),
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    comment: "",
  },
  {
    organization: new Types.ObjectId(8),
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    comment: "",
  },
];
