import { Reimbursement } from "./column-def";

export const data: Reimbursement[] = [
  {
    organization: "123456",
    reportName: "examplename",
    recipientName: "Billy Bob",
    recipientEmail: "billybob@gmail.com",
    transactionDate: new Date("2023-01-01"),
    amount: 500,
    paymentMethod: "Venmo",
    purpose: "Reimbursement for cultural booth event",
    receiptLink: "www.google.com",
    status: "Paid",
    documents: "",
  },
  {
    organization: "13241",
    reportName: "2exampname",
    recipientName: "Jill Andrews",
    recipientEmail: "jillandrews@gmail.com",
    transactionDate: new Date("2023-02-21"),
    amount: 1234.32,
    paymentMethod: "Paypal",
    purpose: "Reimbursement for lunch catering",
    receiptLink: "www.google.com",
    status: "On Hold",
    documents: "",
  },
  {
    organization: "09348",
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    documents: "",
  },
  {
    organization: "09348",
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    documents: "",
  },
  {
    organization: "09348",
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    documents: "",
  },
  {
    organization: "09348",
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    documents: "",
  },
  {
    organization: "09348",
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    documents: "",
  },
  {
    organization: "09348",
    reportName: "examplename",
    recipientName: "Steve Jones",
    recipientEmail: "steve@yahoo.com",
    transactionDate: new Date("2021-12-19"),
    amount: 10.89,
    paymentMethod: "Check",
    purpose: "Reimbursement for craft materials",
    receiptLink: "www.google.com",
    status: "Paid",
    documents: "",
  },
];
